export const metadata = { title: "Terms of Use — Wellbeing" };

export default function TermsPage() {
  const updated = "June 2, 2026";
  return (
    <article className="prose-article">
      <h1 className="font-serif text-3xl text-sage mb-2">Terms of Use</h1>
      <p className="text-sm text-mute mb-8">Last updated: {updated}</p>

      <Section title="Agreement">
        <p>
          By creating an account or using Wellbeing, you agree to these
          terms. If you don&apos;t agree, please don&apos;t use the
          service.
        </p>
      </Section>

      <Section title="Who can use Wellbeing">
        <ul>
          <li>You must be 16 or older.</li>
          <li>
            You agree to provide accurate information when signing up
            (specifically, an email address you control).
          </li>
          <li>
            One account per person. You&apos;re responsible for keeping
            your sign-in email secure.
          </li>
        </ul>
      </Section>

      <Section title="What Wellbeing is — and isn't">
        <p>
          Wellbeing is a software companion for self-reflection and
          general emotional support. It is{" "}
          <strong>
            not a medical device, not a substitute for therapy,
            counselling, or psychiatric care, and not appropriate for
            emergencies.
          </strong>
        </p>
        <p>
          If you are in crisis, in danger of harming yourself or others,
          or experiencing a psychiatric emergency, please contact a
          qualified professional or one of the helplines listed on our{" "}
          <a href="/crisis-resources">Crisis Resources</a> page.
        </p>
      </Section>

      <Section title="Acceptable use">
        <p>You agree not to:</p>
        <ul>
          <li>
            Use the service to harass, threaten, or harm another person.
          </li>
          <li>
            Attempt to extract, copy, or scrape the underlying models, or
            use the service to build a competing product.
          </li>
          <li>
            Circumvent the rate limits or safety classifier in any way.
          </li>
          <li>
            Impersonate another person or sign up with someone else&apos;s
            email.
          </li>
          <li>
            Use the service to obtain medical, legal, or financial advice
            you intend to rely on.
          </li>
        </ul>
        <p>
          We may suspend or terminate accounts that violate these rules.
        </p>
      </Section>

      <Section title="Your content">
        <p>
          You own what you write or speak. By using the service you grant
          us a non-exclusive licence to store and process your content
          solely for the purpose of operating Wellbeing for you. We do
          not publish, share, or sell your content. See our{" "}
          <a href="/legal/privacy">Privacy Policy</a> for full detail.
        </p>
      </Section>

      <Section title="Disclaimers">
        <p>
          The service is provided <strong>&quot;as is&quot;</strong>. We
          do not warrant that the service will be uninterrupted,
          error-free, or that the responses generated by the AI Companion
          will be accurate, complete, or suitable for any purpose. Your
          use of the service is at your own risk.
        </p>
        <p>
          See our <a href="/legal/disclaimer">Disclaimer</a> for the full
          terms on clinical use, emergencies, and the limits of AI advice.
        </p>
      </Section>

      <Section title="Limitation of liability">
        <p>
          To the maximum extent permitted by law, we shall not be liable
          for any indirect, incidental, special, consequential, or
          punitive damages arising from your use of the service. Our
          total liability in any matter shall not exceed the amount you
          paid us in the twelve months before the claim (or, if you have
          paid us nothing, the equivalent of ₹1,000).
        </p>
      </Section>

      <Section title="Termination">
        <p>
          You can delete your account at any time by emailing{" "}
          <a href="mailto:hello@adityeah.ai">hello@adityeah.ai</a>. We may
          terminate or suspend your account if you violate these terms.
          Sections about content licence, disclaimers, and liability
          survive termination.
        </p>
      </Section>

      <Section title="Governing law">
        <p>
          These terms are governed by the laws of India. Any dispute
          shall be subject to the exclusive jurisdiction of the courts of
          Bengaluru, Karnataka.
        </p>
      </Section>

      <Section title="Contact">
        <p>
          Questions or concerns:{" "}
          <a href="mailto:hello@adityeah.ai">hello@adityeah.ai</a>.
        </p>
      </Section>
    </article>
  );
}

function Section({
  title,
  children,
}: {
  title: string;
  children: React.ReactNode;
}) {
  return (
    <section className="mb-7">
      <h2 className="font-serif text-xl text-sage mb-3">{title}</h2>
      <div className="text-[15px] leading-relaxed text-ink space-y-3 [&_ul]:list-disc [&_ul]:pl-6 [&_ul]:space-y-1.5 [&_a]:text-sage [&_a]:underline">
        {children}
      </div>
    </section>
  );
}
